### ISSUE TITLE
Separar imágenes

### ISSUE THREAD

**Issue by LuisJoseSanchez** [joseantoniorosales/MyEntertainmentList#1]
Las imágenes que aparecen en el `README.md` y que están en la misma línea aparecen pegadas. Se debería introducir alguna separación, aunque sea un espacio.

**Comment by joseantoniorosales** [comment]
Arreglado, he reestructurado las imágenes en tablas para alinearlas con el espaciado adecuado y para que estén más organizadas en general

**Comment by LuisJoseSanchez** [comment]
Queda perfecto 👍🏻
